embedder:
  provider: openai
  config:
    model: 'text-embedding-3-small'

llm:
  provider: openai
  config:
    model: 'gpt-3.5-turbo'
    temperature: 0.5
    max_tokens: 1000
    top_p: 1
    stream: false
    api_key: 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
    prompt: |
      Utilisez les éléments de contexte suivants pour répondre à la requête à la fin. Si vous ne connaissez pas la réponse, contentez-vous de dire que vous ne savez pas, ne cherchez pas à inventer une réponse.

      $context

      Query: $query

      Helpful Answer:
    system_prompt: |
      Agissez comme un être humain tres gentil et serviable, et répondez en français, ramener interlocuteur si hors contexte.
